### PR TITLE
Todolist interactive

### PR DESCRIPTION
**Pull request by storres20**
# In this milestone I did the following activities:
- I add "todolistInteractive" branch
- I use webpack
- I add html, css and javascript files for toDoList project
- I add modules for completed
- I checked the linters

### CODE REVIEW

**Review by Alfredbis29 — CHANGES_REQUESTED** [review]
Hi @storres20 
Good job so far! :clap: :clap: :clap:
There are some issues that you still need to work on to go to the next project but you're almost there!

 the-simpsons-homer-simpson

 ## To Highlight 
:white_check_mark: You used Gitflow correctly 
:white_check_mark: Linter checks passed 
:white_check_mark: App is nicely styled :+1:
:white_check_mark: Add, remove, indexing features implemented correctly :+1:
 
 ## Required Changes 
 
- [ ] I see that you have put in a lot of effort on this milestone of your project, but there is something you need to do for your project to be approved. When I try to run your project and add tasks, I get the error shown below; please repair this error so that your project meets all requirements. :point_down: 
 
clasic

 ## Optional suggestions
-N/A
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by storres20** [comment]
Greetings!!!
Thanks for your suggestion but currently the code runs very well

Here's the browser
image

And also, no issues on visual studio code
image

the command that I use for running is: `npm run start`

**Comment by Alfredbis29** [comment]
Hello @storres20 if now everything works good you can ask for the other review and see , good luck

**Review by emmiiorji — APPROVED** [review]
Hi @storres20, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Red-approved

## Good Highlights

- Linter checks are passing
- Adherence to GitHub flow
- Repo is professional
- Good commit messages


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
